<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="N005171" ignored="0" tests="4" failures="1" timestamp="02 Aug 2019 14:16:15 GMT" time="33.663" errors="0">
  <testcase name="SearchOwnerTest" time="7.021" classname="Search_Pet_Owners_Test"/>
  <testcase name="SearchOwnerTest" time="5.488" classname="Search_Pet_Owners_Test"/>
  <testcase name="SearchOwnerTest" time="4.635" classname="Search_Pet_Owners_Test">
    <failure type="java.lang.AssertionError" message="expected [0] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [1]
at Search_Pet_Owners_Test.SearchOwnerTest(Search_Pet_Owners_Test.java:110)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- SearchOwnerTest -->
  <testcase name="SearchOwnerTest" time="15.172" classname="Search_Pet_Owners_Test"/>
</testsuite>
